version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - ewanharris
  ignore:
  - dependency-name: fs-extra
    versions:
    - "> 5.0.0"
  - dependency-name: walk-sync
    versions:
    - "> 0.3.2"
